import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
   
      <body>
      <nav className='navbar flex bg-black text-white h-10 items-center justify-end p-5 gap-5'>

    <Link href='/about'>Home</Link>
    <Link href='/about'>About me</Link>
    <Link href='/about'>Skills</Link>
    <Link href='/about'>Portfoli</Link>
    <button className='contact-btn rounded-xl bg-white text-black text-xs p-1'><Link href='/'>CONTACT ME</Link></button>
      </nav>
        {children}
        </body>
    </html>
  )
}
